# Generated by Django 4.1.1 on 2022-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='cost',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
